Messages:
  Prefix: '&8[&6VirtualVaults&8] &7'
  BuyVault: 'You Have Just Bought a New Vault&8:&7 &6{0}&7!'
  UpVault: 'You Have Just Upgraded Your Vault&8:&7 &6{0}&7!'
  UpVault_Upgraded: '&cYour Vault&8:&c &6{0}&c, Is Already Upgraded!'
  Vault_None: '&cYou Do Not Have Any Vaults!'
  Vault_Saved: 'Your Vault&8:&7 &6{0}&7 - Has Been Saved!'
  TooPoor: '&cYou Can Not Afford to do This! This costs &6{0}&c!'
  EconFail: '&cError&8:&c Economy Failure'
  NoPerm: '&cYou Do Not Have Permission To Do that!'
  NoPerm_Place: '&cYou Do Not Have Permission To Place Vault Signs!'
  NoPerm_Buy: '&cYou Do Not Have Permission To Buy Vaults!'
  NoPerm_Up: '&cYou Do Not Have Permission To Upgrade Your Vault!'
  NoPerm_Open: '&cYou Do Not Have Permission To Open Vaults!'

Prices:
  Buy: 1000
  Up: 900

Permissions:
  Place: 'jailed.vaults.place'
  Buy: 'jailed.vaults.buy'
  Up: 'jailed.vaults.up'
  Open: 'jailed.vaults.open'

Signs:
  BuyVault:
    0: '&8[&cBuy V&8]'
    1: 'Buy a Vault'
    2: 'to Store All'
    3: 'of Your Items'
  UpVault:
    0: '&8[&cUp V&8]'
    1: 'Upgrade Your'
    2: 'Vault to a'
    3: 'Large Vault'
  Vault:
    0: '&8[&cVault&8]'
    1: 'Store All of'
    2: 'Your Items'
    3: 'Here'